update project structure and use latest apis
neptune-ai/project-images-segmentation pull request #4
Opened 2023-01-21 18:10 UTC by kshitij12345

2023-01-23 11:57 UTC, kshitij12345 commented
@SiddhantSadangi can you please do a review to see if I missed something? Thank you :)

2023-01-23 14:44 UTC, SiddhantSadangi requested changes
Can you run this e2e in the original [project-images-segmentation](https://app.neptune.ai/o/common/org/project-images-segmentation) and update the `Overview` dashboard with the changes?

2023-01-23 14:44 UTC, SiddhantSadangi commented on ci_evaluate.py
> +os.environ["NEPTUNE_PROJECT"] = "common/project-images-segmentation-update"
```suggestion
os.environ["NEPTUNE_PROJECT"] = "common/project-images-segmentation"
```

2023-01-23 14:44 UTC, SiddhantSadangi commented on ci_monitoring.py
> +os.environ["NEPTUNE_PROJECT"] = "common/project-images-segmentation-update"
```suggestion
os.environ["NEPTUNE_PROJECT"] = "common/project-images-segmentation"
```

2023-01-23 14:44 UTC, SiddhantSadangi commented on finetune.py
> +    os.environ["NEPTUNE_PROJECT"] = "common/project-images-segmentation-update"
```suggestion
    os.environ["NEPTUNE_PROJECT"] = "common/project-images-segmentation"
```

2023-01-23 14:44 UTC, SiddhantSadangi commented on notebooks/FetchRunMetadata.ipynb
> +    "project = neptune.init_project()\n",
`NEPTUNE_PROJECT` hasn't been set

2023-01-23 14:44 UTC, SiddhantSadangi commented on notebooks/ProjectMetaData.ipynb
> +    "project = neptune.init_project()\n",
`NEPTUNE_PROJECT` hasn't been set

2023-01-23 14:44 UTC, SiddhantSadangi commented on notebooks/ProjectMetaData.ipynb
> +    "model = neptune.init_model(name=\"Prediction Model\", key=\"MOD\", project=\"common/project-images-segmentation-update\")"
```suggestion
    "model = neptune.init_model(name=\"Prediction Model\", key=\"MOD\")"
```

2023-01-23 14:44 UTC, SiddhantSadangi commented on train.py
> +        model_version = neptune.init_model_version(model="IMG-MOD")
```suggestion
        model_version = neptune.init_model_version(model="IMGSEG-MOD")
```

2023-01-23 14:44 UTC, SiddhantSadangi commented on train.py
>          help="number of epochs to train (default: 25)",
```suggestion
        help="number of epochs to train (default: 10)",
```

2023-01-24 05:15 UTC, kshitij12345 commented
Ah, sorry I forgot to mention this is just to verify correct use of new API, I don't intend to merge this.

We are logging to `project-images-segmentation-update` for testing and iterating.

2023-01-24 05:15 UTC, kshitij12345 commented on notebooks/ProjectMetaData.ipynb
> +    "project = neptune.init_project()\n",
Thanks!

2023-01-24 05:15 UTC, kshitij12345 commented on notebooks/FetchRunMetadata.ipynb
> +    "project = neptune.init_project()\n",
Thanks!

2023-01-24 09:59 UTC, SiddhantSadangi requested changes
Just a few leftover `log()` methods

2023-01-24 09:59 UTC, SiddhantSadangi commented on train.py
>          run["data/samples/images"].log(File.as_image(outline_image), name=fname)
```suggestion
        run["data/samples/images"].append(File.as_image(outline_image), name=fname)
```

2023-01-24 09:59 UTC, SiddhantSadangi commented on train.py
>              run["training/metrics/train_dice_loss"].log(loss.item())
```suggestion
            run["training/metrics/train_dice_loss"].append(loss.item())
```

2023-01-24 09:59 UTC, SiddhantSadangi commented on train.py
>                  run["training/metrics/validation_dice_loss"].log(loss.item())
```suggestion
                run["training/metrics/validation_dice_loss"].append(loss.item())
```

2023-01-24 09:59 UTC, SiddhantSadangi commented on train.py
>                                  run[f"training/validation_prediction_progression/{fname}"].log(
```suggestion
                                run[f"training/validation_prediction_progression/{fname}"].append(
```

2023-01-24 09:59 UTC, SiddhantSadangi commented on train.py
>              # corresponding dice coefficient
`run["training/metrics/validation_dice_coefficient"].append(mean_dsc)`

2023-01-24 09:59 UTC, SiddhantSadangi commented on train.py
>      model_vis.render("model_vis")
```suggestion
```
we don't need these anymore

2024-05-28 08:49 UTC, closed without merging